CREATE USER 'pmb'@'localhost' IDENTIFIED BY 'pmb';
GRANT USAGE ON *.* TO 'pmb'@'localhost' IDENTIFIED BY 'pmb' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE DATABASE IF NOT EXISTS `pmb` ;
GRANT ALL PRIVILEGES ON `pmb`.* TO 'pmb'@'localhost';